### ISSUE TITLE
followUser is not working

### ISSUE THREAD

**Issue by ChristopherTrimboli** [ai16z/agent-twitter-client#11]
```
truth_terminal
1802642686710837249
1802642686710837249

/home/cjft/Documents/github/matrix-one/matrix-agent/backend/node_modules/agent-twitter-client/dist/node/cjs/index.cjs:1531
    throw new Error(`Failed to get user ID: ${userIdResult.err.message}`);
          ^

Error: Failed to get user ID: User not found.
    at followUser (/home/cjft/Documents/github/matrix-one/matrix-agent/backend/node_modules/agent-twitter-client/dist/node/cjs/index.cjs:1531:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Scraper.followUser (/home/cjft/Documents/github/matrix-one/matrix-agent/backend/node_modules/agent-twitter-client/dist/node/cjs/index.cjs:3047:5)
```

Verified passing right userId to follow user but breaking.

**Comment by kingbootoshi** [comment]
can you show the code you're using ?
